### ISSUE TITLE
Smart cut: `Could not find a valid device`; `can't configure encoder`

### ISSUE THREAD

**Issue by jtagcat** [flathub/no.mifi.losslesscut#22]
[#126 ](https://github.com/mifi/lossless-cut/issues/126)

`x.mp4` has followed the path of:
1. OBS 
2. `ffmpeg -hide_banner -loglevel warning -i "$1" -map 0 -c copy -c:v libx265 "$2"`
3. LosslessCut a segment without smart cut
4.`ffmpeg -hide_banner -loglevel warning -i "$1" -preset slow -map 0 -c copy -c:v libx264 -crf 23 -c:a aac -movflags faststart "x.mp4"`
5. LosslessCut attempt to smart cut

https://q.c7.ee/losslesscut_1150/x.mp4
https://q.c7.ee/losslesscut_1150/x-proj.llc

**Failure log**
```
Error: Command failed with exit code 1: /app/lossless-cut/resources/ffmpeg -hide_banner -i /home/jc/dl/x.mp4 -ss 5.54261 -t 0.49073 -map 0:0 -c:0 h264 -b:0 1941286 -map 0:1 -c:1 copy -ignore_unknown -video_track_timescale 15360 -f mp4 -y /home/jc/dl/x-smartcut-segment-encode-0.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/jc/dl/x.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Duration: 00:00:16.90, start: 0.000000, bitrate: 2080 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 1941 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_v4l2m2m))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0x559d1ca1e140] Could not find a valid device
[h264_v4l2m2m @ 0x559d1ca1e140] can't configure encoder
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
    at makeError (/app/lossless-cut/resources/app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/lossless-cut/resources/app/node_modules/execa/index.js:118:26)
    at async d_.filePath (file:///app/lossless-cut/resources/app/build/static/js/main.276ec257.js:2:309229)
    at async file:///app/lossless-cut/resources/app/build/static/js/main.276ec257.js:2:308729
    at async file:///app/lossless-cut/resources/app/build/static/js/main.276ec257.js:2:2446984

{
  "err": {
    "killed": false,
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "exitCode": 1
  },
  "state": {
    "filePath": "/home/jc/dl/x.mp4",
    "fileFormat": "mp4",
    "mainStreams": [
      {
        "index": 0,
        "codec_name": "h264",
        "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        "profile": "High",
        "codec_type": "video",
        "codec_time_base": "1/60",
        "codec_tag_string": "avc1",
        "codec_tag": "0x31637661",
        "width": 640,
        "height": 480,
        "coded_width": 640,
        "coded_height": 480,
        "closed_captions": 0,
        "has_b_frames": 2,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "4:3",
        "pix_fmt": "yuv420p",
        "level": 30,
        "chroma_location": "left",
        "refs": 1,
        "is_avc": "true",
        "nal_length_size": "4",
        "r_frame_rate": "30/1",
        "avg_frame_rate": "30/1",
        "time_base": "1/15360",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 259584,
        "duration": "16.900000",
        "bit_rate": "1941286",
        "bits_per_raw_sample": "8",
        "nb_frames": "507",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "VideoHandler",
          "vendor_id": "[0][0][0][0]"
        }
      },
      {
        "index": 1,
        "codec_name": "aac",
        "codec_long_name": "AAC (Advanced Audio Coding)",
        "profile": "LC",
        "codec_type": "audio",
        "codec_time_base": "1/44100",
        "codec_tag_string": "mp4a",
        "codec_tag": "0x6134706d",
        "sample_fmt": "fltp",
        "sample_rate": "44100",
        "channels": 2,
        "channel_layout": "stereo",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/44100",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 742512,
        "duration": "16.837007",
        "bit_rate": "127894",
        "max_bit_rate": "128000",
        "nb_frames": "726",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "und",
          "handler_name": "SoundHandler",
          "vendor_id": "[0][0][0][0]"
        }
      }
    ],
    "copyStreamIdsByFile": {
      "/home/jc/dl/x.mp4": {
        "0": true,
        "1": true
      }
    },
    "cutSegments": [
      {
        "start": 5.542606149341141,
        "end": 9.625329428989751
      }
    ],
    "mainFileFormatData": {
      "filename": "/home/jc/dl/x.mp4",
      "nb_streams": 2,
      "nb_programs": 0,
      "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
      "format_long_name": "QuickTime / MOV",
      "start_time": "0.000000",
      "duration": "16.900000",
      "size": "4394086",
      "bit_rate": "2080040",
      "probe_score": 100,
      "tags": {
        "major_brand": "isom",
        "minor_version": "512",
        "compatible_brands": "isomiso2avc1mp41",
        "encoder": "Lavf59.16.100"
      }
    },
    "rotation": 360,
    "shortestFlag": false
  },
  "platform": "linux",
  "version": "3.44.0"
}
```
When running manually:
```
ffmpeg -hide_banner -i /home/jc/dl/x.mp4 -ss 5.54261 -t 0.49073 -map 0:0 -c:0 h264 -b:0 1941286 -map 0:1 -c:1 copy -ignore_unknown -video_track_timescale 15360 -f mp4 -y /home/jc/dl/x-smartcut-segment-encode-0.mp4
```

The output file contains video until the first keyframe in the cut. I've never seen the smart cut feature work, so I'm guessing it'll join parts together.

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Package: Flatpak https://github.com/flathub/no.mifi.losslesscut (LC is not available via dnf; snap and Appimage are a chore to deal wth)

***

This is probably due to missing dependencies in the package.

**Comment by muelli** [comment]
hm.
I cannot make anything out of this bug report.
Can you try with the current version? It has ffmpeg 6 and it might work better.

**Comment by jtagcat** [comment]
Can't reproduce any more either.

**Comment by MoralCode** [comment]
im seeing this issue. installed via flatpack on fedora 40. also observed during attempted smartcut of an h264 video
